import type { WikiWebConfig } from '../models/config';

export const defaultConfig: WikiWebConfig = {
  schemaVersion: 1,
  zoomSpacingMode: 'equal-stage',
  nodeTypes: [
    {
      id: 'major-concept',
      label: 'Major Concept',
      color: '#0055ff',
      size: 72,
      titleDetailLevel: 1,
      reveal: {
        hidden: 0,
        bubble: 1,
        title: 1,
        summary: 2,
        children: 3,
        article: 4,
      },
      defaultArticleRank: 2,
    },
    {
      id: 'concept',
      label: 'Concept',
      color: '#0077cc',
      size: 64,
      titleDetailLevel: 4,
      reveal: {
        hidden: 0,
        bubble: 1,
        title: 2,
        summary: 3,
        children: 4,
        article: 5,
      },
      defaultArticleRank: 3,
    },
    {
      id: 'collection',
      label: 'Collection',
      color: '#009966',
      size: 66,
      titleDetailLevel: 5,
      reveal: {
        hidden: 0,
        bubble: 1,
        title: 2,
        summary: 3,
        children: 4,
        article: 5,
      },
      defaultArticleRank: 13,
    },
    {
      id: 'notation',
      label: 'Notation',
      color: '#8800aa',
      size: 56,
      titleDetailLevel: 5,
      reveal: {
        hidden: 0,
        bubble: 1,
        title: 2,
        summary: 3,
        children: 4,
        article: 5,
      },
      defaultArticleRank: 1,
    },
    {
      id: 'visualization',
      label: 'Visualization',
      color: '#cc5500',
      size: 60,
      titleDetailLevel: 5,
      reveal: {
        hidden: 0,
        bubble: 1,
        title: 2,
        summary: 3,
        children: 4,
        article: 5,
      },
      defaultArticleRank: 3,
    },
    {
      id: 'proof',
      label: 'Proof',
      color: '#aa0000',
      size: 56,
      titleDetailLevel: 18,
      reveal: {
        hidden: 0,
        bubble: 1,
        title: 2,
        summary: 3,
        children: 4,
        article: 5,
      },
      defaultArticleRank: 4,
    },
    {
      id: 'definition',
      label: 'Definition',
      color: '#006600',
      size: 58,
      titleDetailLevel: 5,
      reveal: {
        hidden: 0,
        bubble: 1,
        title: 2,
        summary: 3,
        children: 4,
        article: 5,
      },
      defaultArticleRank: 5,
    },
    {
      id: 'example',
      label: 'Example',
      color: '#cc7700',
      size: 56,
      titleDetailLevel: 5,
      reveal: {
        hidden: 0,
        bubble: 1,
        title: 2,
        summary: 3,
        children: 4,
        article: 5,
      },
      defaultArticleRank: 6,
    },
    {
      id: 'counterexample',
      label: 'Counterexample',
      color: '#cc0000',
      size: 56,
      titleDetailLevel: 5,
      reveal: {
        hidden: 0,
        bubble: 1,
        title: 2,
        summary: 3,
        children: 4,
        article: 5,
      },
      defaultArticleRank: 7,
    },
    {
      id: 'theorem',
      label: 'Theorem',
      color: '#5500cc',
      size: 58,
      titleDetailLevel: 5,
      reveal: {
        hidden: 0,
        bubble: 1,
        title: 2,
        summary: 3,
        children: 4,
        article: 5,
      },
      defaultArticleRank: 8,
    },
    {
      id: 'conjecture',
      label: 'Conjecture',
      color: '#770099',
      size: 56,
      titleDetailLevel: 5,
      reveal: {
        hidden: 0,
        bubble: 1,
        title: 2,
        summary: 3,
        children: 4,
        article: 5,
      },
      defaultArticleRank: 9,
    },
    {
      id: 'question',
      label: 'Question',
      color: '#0099cc',
      size: 56,
      titleDetailLevel: 5,
      reveal: {
        hidden: 0,
        bubble: 1,
        title: 2,
        summary: 3,
        children: 4,
        article: 5,
      },
      defaultArticleRank: 10,
    },
    {
      id: 'historical-note',
      label: 'Historical Note',
      color: '#666666',
      size: 56,
      titleDetailLevel: 5,
      reveal: {
        hidden: 0,
        bubble: 1,
        title: 2,
        summary: 3,
        children: 4,
        article: 5,
      },
      defaultArticleRank: 11,
    },
    {
      id: 'source',
      label: 'Source',
      color: '#333333',
      size: 52,
      titleDetailLevel: 5,
      reveal: {
        hidden: 0,
        bubble: 1,
        title: 2,
        summary: 3,
        children: 4,
        article: 5,
      },
      defaultArticleRank: 12,
    },
    {
      id: 'personal-annotation',
      label: 'Personal Annotation',
      color: '#aa5500',
      size: 52,
      titleDetailLevel: 5,
      reveal: {
        hidden: 0,
        bubble: 1,
        title: 2,
        summary: 3,
        children: 4,
        article: 5,
      },
      defaultArticleRank: 13,
    },
    {
      id: 'other-collection',
      label: 'Other Collection',
      color: '#444444',
      size: 54,
      titleDetailLevel: 5,
      reveal: {
        hidden: 0,
        bubble: 1,
        title: 2,
        summary: 3,
        children: 4,
        article: 5,
      },
      defaultArticleRank: 14,
    },
  ],
  defaultArticleOrder: [
    'notation',
    'direct-body-content',
    'visualization',
    'proof',
    'definition',
    'example',
    'counterexample',
    'theorem',
    'conjecture',
    'question',
    'historical-note',
    'source',
    'personal-annotation',
    'other-collection',
  ],
  defaultEdgeStrength: 1,
  neutralPeerEdgeColor: '#888888',
};
